// Auto-generated by packages/hardhat/scripts/deploy.ts
export const PASSPORT_CONTRACT = "0xc7b4766115ca5d2002f3bf94e79978d8bbbd45e0" as const;
export const EVENTLOG_CONTRACT = "0x8637064d922f9a061f1b36a58888a34f477a8158" as const;
export const DEPLOYED_AT = "2026-10-03T08:27:38.109Z" as const;
export const CHAIN_ID = 296 as const;
