import hre from "hardhat";
import { writeFileSync, appendFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../../..");

/**
 * Deploys AgentEventLog + AgentPassportNFT to Hedera (HSCS/EVM).
 * Writes deployed addresses to `packages/app/deployedContracts.ts` and
 * appends them to the repo-root `.env` as PASSPORT_CONTRACT / EVENTLOG_CONTRACT.
 */
async function main() {
  const conn = await hre.network.connect();
  const viem = conn.viem;
  const publicClient = await viem.getPublicClient();
  const [deployer] = await viem.getWalletClients();
  const admin = deployer.account.address;

  console.log(
    `Deploying from ${admin} on chain ${await publicClient.getChainId()}…`,
  );

  // 1. Event log — writer will be the passport contract (set below).
  const log = await viem.deployContract("AgentEventLog", [admin]);
  console.log(`AgentEventLog deployed: ${log.address}`);

  // 2. Passport NFT — admin holds MINTER_ROLE + REVOKER_ROLE.
  const passport = await viem.deployContract("AgentPassportNFT", [
    log.address,
    admin,
  ]);
  console.log(`AgentPassportNFT deployed: ${passport.address}`);

  // 3. Allow the passport contract to write to the event log.
  const setWriterHash = await log.write.setWriter([passport.address]);
  await publicClient.waitForTransactionReceipt({ hash: setWriterHash });
  console.log("setWriter(passport) — done");

  // 4. Persist addresses for the app package.
  const deployed = `// Auto-generated by packages/hardhat/scripts/deploy.ts
export const PASSPORT_CONTRACT = "${passport.address}" as const;
export const EVENTLOG_CONTRACT = "${log.address}" as const;
export const DEPLOYED_AT = "${new Date().toISOString()}" as const;
export const CHAIN_ID = ${await publicClient.getChainId()} as const;
`;
  const appDir = resolve(repoRoot, "packages/app");
  mkdirSync(appDir, { recursive: true });
  const outFile = resolve(appDir, "deployedContracts.ts");
  writeFileSync(outFile, deployed);
  console.log(`Wrote ${outFile}`);

  const envFile = resolve(repoRoot, ".env");
  const envLines = `PASSPORT_CONTRACT=${passport.address}\nEVENTLOG_CONTRACT=${log.address}\n`;
  if (existsSync(envFile)) {
    appendFileSync(envFile, envLines);
    console.log(`Appended contract addresses to ${envFile}`);
  } else {
    writeFileSync(envFile, envLines);
    console.log(`Created ${envFile} with contract addresses`);
  }

  console.log("\nDone. Next: npm run smoke -w packages/hardhat");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
