import hre from "hardhat";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../../..");

/**
 * Smoke check: mint one passport NFT + emit one event-log topic, then print
 * Hashscan links for the bounty eligibility gate (verifiable testnet tx).
 * Requires PASSPORT_CONTRACT / EVENTLOG_CONTRACT in .env (written by deploy.ts).
 */
async function main() {
  const passportAddr = process.env.PASSPORT_CONTRACT as `0x${string}`;
  const logAddr = process.env.EVENTLOG_CONTRACT as `0x${string}`;
  if (!passportAddr || !logAddr) {
    throw new Error(
      "PASSPORT_CONTRACT / EVENTLOG_CONTRACT missing — run `npm run deploy` first",
    );
  }

  const conn = await hre.network.connect();
  const viem = conn.viem;
  const [deployer] = await viem.getWalletClients();
  const me = deployer.account.address;

  const passport = await viem.getContractAt("AgentPassportNFT", passportAddr, {
    client: { wallet: deployer },
  });
  const log = await viem.getContractAt("AgentEventLog", logAddr, {
    client: { wallet: deployer },
  });

  // Smoke mint — tier 1 (bronze) passport to the deployer.
  const mintHash = await passport.write.mint([
    me,
    "ipfs://template-agent-passport/smoke",
    1,
  ]);
  console.log(`mint tx: ${mintHash}`);

  // Direct event-log write (deployer is still `writer` until you re-point it).
  // If writer was moved to the passport contract this will revert — that's OK,
  // the mint above already emits via the contract. Try it, but don't fail hard.
  let emitHash: string | null = null;
  try {
    emitHash = await log.write.emitTopic([
      "smoke",
      "0x" + Buffer.from("template smoke event").toString("hex"),
    ] as [`0x${string}` | string, `0x${string}`]);
    console.log(`emitTopic tx: ${emitHash}`);
  } catch {
    console.log(
      "emitTopic skipped (writer is the passport contract — expected).",
    );
  }

  const net =
    (await viem.getPublicClient()).chain?.id === 295 ? "mainnet" : "testnet";
  const links = [
    `https://hashscan.io/${net}/transaction/${mintHash}`,
    ...(emitHash ? [`https://hashscan.io/${net}/transaction/${emitHash}`] : []),
  ];
  console.log("\nHashscan links:");
  for (const l of links) console.log(`  ${l}`);

  const md = `# Deployments

Generated by \`npm run smoke -w packages/hardhat\` on ${new Date().toISOString()}.

| Item | Value |
| ---- | ----- |
| Network | Hedera ${net} (chainId ${(await viem.getPublicClient()).chain?.id}) |
| AgentPassportNFT | \`${passportAddr}\` |
| AgentEventLog | \`${logAddr}\` |
| Deployer | \`${me}\` |

## Verifiable transactions

- Mint passport NFT: ${links[0]}
${emitHash ? `- Event log emitTopic: ${links[1]}` : ""}

## Hashscan contracts

- https://hashscan.io/${net}/contract/${passportAddr}
- https://hashscan.io/${net}/contract/${logAddr}
`;
  const out = resolve(repoRoot, "DEPLOYMENTS.md");
  writeFileSync(out, md);
  console.log(`\nWrote ${out}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
